<?php /* @var $this Reverb_ReverbSync_Block_Adminhtml_Sales_Order_View_Tab_Reverb */ ?>

<div class="reverb_order_view_tab">
    <div class="order_id">
        <span class="label">Reverb Order #</span><span class="value"><?php echo $this->getReverbOrderId() ?></span>
    </div>
    <div class="order_status">
        <span class="label">Reverb Order Status: </span><span class="value"><?php echo $this->getReverbOrderStatus() ?></span>
    </div>
</div>