
<?php
$targetProductId = $this -> getRevProductSync();
?>

  <table cellspacing="0" class="form-list">
        <tr>
                    <td class="label"><label for="_targetsync"><?php echo $this -> __('Rev Product ID'); ?></label></td>
                    <td class="value"><?php echo $targetProductId; ?></td>
                    <td id="note_subscription"><small>&nbsp;</small></td>
                </tr>
              <tr>
                    <td class="label"><label for="_targetsync"><?php echo $this -> __('Rev Product URL'); ?></label></td>
                     <td class="value"><a href='<?php echo $targetProductUrl = $this -> getRevProductUrlSync(); ?>'><?php echo $targetProductUrl = $this -> getRevProductUrlSync(); ?></a></td>
                    <td id="note_subscription"><small>&nbsp;</small></td>
                </tr>
  </table>
