
<?php
   if (Mage::getStoreConfig('ReverbSync/extensionOption_group/module_select'))
   {
   
    $ProductSyncUrl = Mage::helper('adminhtml')->getUrl('*/RevOfflineSync_Sync/productSync/product_id/'.$this->getProductId());
     
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this -> __('Reverb  Info'); ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div id="_newsletterbase_fieldset" class="fieldset ">
        <?php
        if ($targetProductId=$this->getTargetProductId()=="") {
            ?>

        <div class="hor-scroll" id="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td>
                                <form name='revsyncform' id='revsyncform' action='' method='get'>
                                   
                                    <button style="" onClick="submitAndReloadArea($('hor-scroll').parentNode, '<?php echo $ProductSyncUrl; ?>')"
                                                class="scalable" type="button" id="rev_product_save">
                                            <span><?php echo $this -> __('Sync'); ?></span>
                                        </button>
                                </form>
                            </td>
                        </tr>
                    </table>
                </div>
        <?php }

        else {
    ?>
        <div id="target_product_id">
            <table cellspacing="0" class="form-list">

                <tr>
                    <td class="label"><label for="_targetsync"><?php echo $this -> __('Reverb Product Id'); ?></label></td>
                    <td class="value"><?php echo $targetProductId = $this -> getTargetProductId(); ?></td>
                    <td id="note_subscription"><small>&nbsp;</small></td>
                </tr>
                <tr>
                    <td class="label"><label for="_targetsync"><?php echo $this -> __('Reverb Product URL'); ?></label></td>
       
                   <td class="value"><a href='<?php echo $targetProductUrl = $this -> getTargetProductUrl(); ?>'><?php echo $targetProductUrl = $this -> getTargetProductUrl(); ?></a></td>
                    <td id="note_subscription"><small>&nbsp;</small></td>
                </tr>
               
            </table>
        </div>
        <?php } ?>
    </div>
</div>
<?php } ?>
<?php echo $this -> getChildHtml('', true, true); ?>

